// <auto-generated />
using System;
using FbiApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FbiApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260126074821_AddReportStatus")]
    partial class AddReportStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FbiApi.Models.Entities.LocationWantedPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WantedPersonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WantedPersonId");

                    b.ToTable("LocationWantedPersons");
                });

            modelBuilder.Entity("FbiApi.Models.Entities.PersonMatchResults", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LocationWantedPersonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LocationWantedPersonId");

                    b.ToTable("PersonMatchResults");
                });

            modelBuilder.Entity("FbiApi.Models.Entities.SaveWantedPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WantedPersonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WantedPersonId");

                    b.ToTable("SaveWantedPersons");
                });

            modelBuilder.Entity("FbiApi.Models.Entities.WantedAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WantedPersonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WantedPersonId");

                    b.ToTable("WantedAliases");
                });

            modelBuilder.Entity("FbiApi.Models.Entities.WantedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<int>("WantedPersonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WantedPersonId");

                    b.ToTable("WantedFiles");
                });

            modelBuilder.Entity("FbiApi.Models.Entities.WantedImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .HasColumnType("text");

                    b.Property<string>("LargeUrl")
                        .HasColumnType("text");

                    b.Property<string>("OriginalUrl")
                        .HasColumnType("text");

                    b.Property<string>("ThumbUrl")
                        .HasColumnType("text");

                    b.Property<int>("WantedPersonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WantedPersonId");

                    b.ToTable("WantedImages");
                });

            modelBuilder.Entity("FbiApi.Models.Entities.WantedPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Build")
                        .HasColumnType("text");

                    b.Property<string>("Caution")
                        .HasColumnType("text");

                    b.Property<string>("Complexion")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Eyes")
                        .HasColumnType("text");

                    b.Property<string>("Hair")
                        .HasColumnType("text");

                    b.Property<int?>("HeightMax")
                        .HasColumnType("integer");

                    b.Property<int?>("HeightMin")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nationality")
                        .HasColumnType("text");

                    b.Property<string>("Ncic")
                        .HasColumnType("text");

                    b.Property<string>("PathId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonClassification")
                        .HasColumnType("text");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PublicationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Race")
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<int?>("RewardMax")
                        .HasColumnType("integer");

                    b.Property<int?>("RewardMin")
                        .HasColumnType("integer");

                    b.Property<string>("RewardText")
                        .HasColumnType("text");

                    b.Property<string>("ScarsAndMarks")
                        .HasColumnType("text");

                    b.Property<string>("Sex")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("WarningMessage")
                        .HasColumnType("text");

                    b.Property<int?>("WeightMax")
                        .HasColumnType("integer");

                    b.Property<int?>("WeightMin")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("WantedPersons");
                });

            modelBuilder.Entity("FbiApi.Models.Entities.WantedSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WantedPersonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WantedPersonId");

                    b.ToTable("WantedSubjects");
                });

            modelBuilder.Entity("FbiApi.Models.Entities.LocationWantedPerson", b =>
                {
                    b.HasOne("FbiApi.Models.Entities.WantedPerson", "WantedPerson")
                        .WithMany("LocationWantedPersons")
                        .HasForeignKey("WantedPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WantedPerson");
                });

            modelBuilder.Entity("FbiApi.Models.Entities.PersonMatchResults", b =>
                {
                    b.HasOne("FbiApi.Models.Entities.LocationWantedPerson", "LocationWantedPerson")
                        .WithMany("personMatchResults")
                        .HasForeignKey("LocationWantedPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocationWantedPerson");
                });

            modelBuilder.Entity("FbiApi.Models.Entities.SaveWantedPerson", b =>
                {
                    b.HasOne("FbiApi.Models.Entities.WantedPerson", "WantedPerson")
                        .WithMany("SaveWantedPersons")
                        .HasForeignKey("WantedPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WantedPerson");
                });

            modelBuilder.Entity("FbiApi.Models.Entities.WantedAlias", b =>
                {
                    b.HasOne("FbiApi.Models.Entities.WantedPerson", "WantedPerson")
                        .WithMany("Aliases")
                        .HasForeignKey("WantedPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WantedPerson");
                });

            modelBuilder.Entity("FbiApi.Models.Entities.WantedFile", b =>
                {
                    b.HasOne("FbiApi.Models.Entities.WantedPerson", "WantedPerson")
                        .WithMany("Files")
                        .HasForeignKey("WantedPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WantedPerson");
                });

            modelBuilder.Entity("FbiApi.Models.Entities.WantedImage", b =>
                {
                    b.HasOne("FbiApi.Models.Entities.WantedPerson", "WantedPerson")
                        .WithMany("Images")
                        .HasForeignKey("WantedPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WantedPerson");
                });

            modelBuilder.Entity("FbiApi.Models.Entities.WantedSubject", b =>
                {
                    b.HasOne("FbiApi.Models.Entities.WantedPerson", "WantedPerson")
                        .WithMany("Subjects")
                        .HasForeignKey("WantedPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WantedPerson");
                });

            modelBuilder.Entity("FbiApi.Models.Entities.LocationWantedPerson", b =>
                {
                    b.Navigation("personMatchResults");
                });

            modelBuilder.Entity("FbiApi.Models.Entities.WantedPerson", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("Files");

                    b.Navigation("Images");

                    b.Navigation("LocationWantedPersons");

                    b.Navigation("SaveWantedPersons");

                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
